import { Roboto, Noto_Sans_KR } from 'next/font/google'
import "../styles/globals.css"
import Header from '../components/Header'
// import Footer from '../components/Footer'

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"], // 또는 preload: false
  weight: ["100", "400", "700", "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const roboto = Roboto({
  subsets: ["latin"], // preload에 사용할 subsets입니다.
  weight: ["100", "400", "700"],
  variable: "--roboto", // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const cls = (...classnames: string[]) => {
  return classnames.join(' ');
}

export default function RootLayout( {children,} : { children: React.ReactNode } ) {
  return (
    <html lang="en">
      <body className={ cls(notoSansKr.className, roboto.variable, "flex" ,"h-screen", "flex-col" , "bg-white" , "text-neutral" )}>
        {/* <Header/> */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  )
}
